const datum = new Date();
const heute = [datum.getDate(), datum.getMonth()+1, datum.getFullYear()]
export const events = [
  { id: 1, eventName: "Geburtstag", eventDate: [13, 9, 2007],eventMoreInfo:`Lieber Ali,
zu deinem Geburtstag gratuliere ich dir von Herzen! Möge dein neues Lebensjahr dir Gesundheit, Glück und unzählige schöne Momente bringen. Heute ist dein Tag, um zu feiern, zu lachen und das Leben in vollen Zügen zu genießen. Ich wünsche dir, dass all deine Träume in Erfüllung gehen und du von lieben Menschen umgeben bist, die dich schätzen.
Dein Engagement und deine positive Ausstrahlung machen jeden Tag heller, und es ist eine Freude, dich zu kennen. Lass uns gemeinsam auf dich anstoßen und diesen besonderen Tag unvergesslich machen! Mögen die kommenden Jahre dir Erfolg, Liebe und viele Abenteuer bringen. Genieße deine Feier und lass dich gebührend verwöhnen!
Herzliche Grüße`, eventDetails: "Ja! Heute ist mein Geburtstag!😍",eventPic:"https://imgs.search.brave.com/WP23WZIG7J_BqeprDxtr72gwiwWa18lk0GRPzXg9hac/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3RpL2ZvdG9z/LWtvc3Rlbmxvcy90/Mi81NzMwMTU1Ny1t/YWNoZW4tZWluLXd1/bnNjaC12ZXJicmVu/bnVuZy1rZXJ6ZW4t/YXVmLWdlYnVydHN0/YWcta3VjaGVuLWJl/cmVpdC16dW0td2Vo/dC1hdXMtZ2x1Y2ts/aWNoLWdlYnVydHN0/YWctcGFydHktZnJl/dW5kZS13dW5zY2h0/LXNpY2gtZnJhdS1n/bHVja2xpY2gtZ2Vi/dXJ0c3RhZy1tZW5z/Y2hlbi1mZWllcm4t/Z2VidXJ0c3RhZy1w/YXJ0eS10ZWxsZXIt/bWl0LWdlYnVydHN0/YWcta3VjaGVuLWlt/LWhhbmRlLWZvdG8u/anBn" },
  { id: 2, eventName: "Test2", eventDate: [15, 1, 2025],eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test" ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/magnific-cat.webp"},
  { id: 3, eventName: "Test3", eventDate: [29, 4, 2025],eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test" ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/resource-tti-15.webp"},
  { id: 4, eventName: "Test4", eventDate: [2, 11, 2025],eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test" ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/65446.webp"},
  { id: 5, eventName: "Test5", eventDate: [30, 7, 2025],eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test" ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/pikaso-dog.webp"},
  { id: 6, eventName: "Test6", eventDate: [7, 5, 2025] ,eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test"  ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/pikaso-man-in-a-red-robe-standing-on-a-cliff.webp"},
  { id: 7, eventName: "Ereignis heute", eventDate: [heute[0],heute[1],heute[2]] ,eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Ereignis, das überall gezeigt wird"  ,eventPic:"heuteIcon.jpg"},
  { id: 8, eventName: "Test7", eventDate: [1, 1, 2026] ,eventMoreInfo:`Die Sonne taucht den Himmel in goldenes Licht, während Vögel über smaragdgrüne Wiesen schweben. Ein sanfter Wind flüstert Geheimnisse durch die Blätter uralter Bäume. In der Ferne plätschert ein Bach, als würde er Geschichten aus den Bergen erzählen. Bunte Schmetterlinge tanzen in der Luft, und der Duft von wilden Blumen erfüllt die Sinne. Die Natur ist ein magischer Ort, der Ruhe und Abenteuer zugleich schenkt. Jeder Schritt auf moosigem Boden fühlt sich wie eine Reise an. Möge dieser Tag dich inspirieren, die Welt draußen zu erkunden und ihre Wunder zu genießen!`, eventDetails: "Dieses ist ein Test"  ,eventPic:"https://cdn-front.freepik.com/images/ai/image-generator/gallery/pikaso-man-in-a-red-robe-standing-on-a-cliff.webp"},
]

